name: Compile and Deploy Website

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Let's prepare our env
      - name: Prepare toolchain
        run: cargo install perseus-cli

      - name: Build and Export Website
        run: perseus --wasm-opt-version version_118 export

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist/exported

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs_on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4