name: Compile and Deploy Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # The website builder accesses Git history for old examples, so we need everything
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Let's prepare our env
      - name: Prepare toolchain
        run: cargo install perseus-cli

      - name: Build and Export Website
        run: perseus --wasm-opt-version version_118 export

      - name: Deploy website to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/exported
